#ifndef SHMQ_H__
#define SHMQ_H__

// uint8
enum
{
	SHMQ_MT_BIT_IN = 0,
	SHMQ_MT_BIT_OUT = 1,
	SHMQ_MT_U8_IN = 2,
	SHMQ_MT_U8_OUT = 3,
	SHMQ_MT_U16_IN = 4,
	SHMQ_MT_U16_OUT = 5,
	SHMQ_MT_U32_IN = 6,
	SHMQ_MT_U32_OUT = 7,
	SHMQ_MT_U64_IN = 8,
	SHMQ_MT_U64_OUT = 9,
	SHMQ_MT_FLOAT_IN = 10,
	SHMQ_MT_FLOAT_OUT = 11,
	SHMQ_MT_DOUBLE_IN = 12,
	SHMQ_MT_DOUBLE_OUT = 13,
	SHMQ_MT_STRING_IN = 14,
	SHMQ_MT_STRING_OUT = 15,

	SHMQ_MT_TD = 16, // u64 time in ms since 1 Jan 1900 00:00:00
}

enum
{
	SH_GW_STS_PWR = 0,
	SH_GW_STS_TIME,
	SH_GW_STS_ONTIME,
	SH_GW_STS_VIN,
	SH_GW_STS_VOUT,
	SH_GW_STS_ILOAD,
	SH_GW_STS_ENERGY,
	SH_GW_STS_POWER,
}

enum
{
	SH_CMD_ACK = 0, // u8 counter
	SH_CMD_RST,
	SH_CMD_STS,
	SH_CMD_PON,
	SH_CMD_POFF,
	SH_CMD_SDOR,
	SH_CMD_SDOW,
}

#endif // SHMQ_H__